### PR TITLE
FlipCard!

### PR DESCRIPTION
**Pull request by Ploypiti**
Actually _FlashCard_ but it's flippable and _FlipCard_ sounds cool.

**screenshot**

image
image

No merge conflict, I feel so pure & decent.
Issue #1 

tenor

### CODE REVIEW

**Comment by nisaruj** [comment]
Thanks! It works like a charm✨✨.

**Comment by Ploypiti** [comment]
How long did you take to google _how to comment in GitHub_?

**Comment by nisaruj** [comment]
so long and still haven't found :(
I think that commenting in my style is better.

**Comment by Ploypiti** [comment]
Maybe try to mind your grammar instead.

**Comment by nisaruj** [comment]
😢

**Pull request merged**
